Repository DonIsaac/oxbuild, pull requests merged in 2024-09, with the labels that each got.

#1 feat(cli): add `--threads` argument
  Cargo.toml
  Justfile
  src/cli.rs
  src/main.rs
  src/options.rs
Labels: enhancement

#2 feat(cli): add pretty error reporting
  src/compiler/mod.rs
  src/main.rs
  src/options.rs
  src/reporter.rs
  src/walk.rs
Labels: enhancement

#18 docs: Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#19 ci: check for typos and unused dependencies
  .github/workflows/ci.yml
  .typos.toml
  src/options.rs
Labels: ci

#21 feat(cli): specify root directory as a CLI argument
  Justfile
  src/cli.rs
  src/cli/root.rs
Labels: enhancement

#20 release installers and binaries!
  .github/workflows/release.yml
  Cargo.toml
Labels: ci

#25 fix(cli): PathBuf parsing for CLI args
  Cargo.toml
  src/cli.rs
Labels: bug

#27 ci: publish to npm
  .github/workflows/release.yml
  Cargo.toml
Labels: ci

#28 feat: exit with non-zero code when errors occur
  src/main.rs
  src/reporter.rs
Labels: enhancement
